### ISSUE TITLE
Issues with GIFs

### ISSUE THREAD

**Issue by tortilaman** [punkave/uploadfs#37]
I've run into a very odd issue with gifs. It revolves around JIMP, but I haven't seen it mentioned there, so I'm not 100% sure yet whether the issue is with JIMP, or with this particular implementation of it.

When trying to upload a gif with `apostrophe-images`, it gives the generic image error in the browser, and on the server, it gives the following error output:
```
Unsupported MIME type: image/gif
Unsupported MIME type: image/gif
Unsupported MIME type: image/gif
Unsupported MIME type: image/gif
Unsupported MIME type: image/gif
Unsupported MIME type: image/gif
TypeError: Cannot read property 'bitmap' of undefined
    at Jimp.<anonymous> (/Users/nick/Development/annual-report/cms/node_modules/apostrophe/node_modules/uploadfs/lib/image/jimp.js:46:34)
    at Jimp.throwError (/Users/nick/Development/annual-report/cms/node_modules/jimp/index.js:85:44)
    at ReadFileContext.callback (/Users/nick/Development/annual-report/cms/node_modules/jimp/index.js:201:44)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)
```

Jimp knows what the MIME type is in previous functions, and has a conditional to handle `image/gif` specifically, yet when it gets here, the `image` variable is undefined. Let me know if there's more information I can provide, I'm not the best at debugging, haha.

**Comment by boutell** [comment]
Happens with every gif?

**Comment by boutell** [comment]
Jimp is the slowest option btw but of course we want it to work too because
it is the zero effort option.

**Comment by tortilaman** [comment]
I tried it with several different gifs. Different tools were used to export them and I had them exported at different sizes.

I was a bit confused why it was trying to use Jimp and not ImageMagick or something else.

**Comment by boutell** [comment]
You have to have the imagemagick convert and identify utilities in your
PATH.

**Comment by tortilaman** [comment]
Ah, that might be difficult with cloud hosting. I'll look into it. Thanks for the info.

**Comment by boutell** [comment]
Heroku has it. Amazon EC2, you can install it from package manager at
startup of the instance, for instance via etc/rc.local

**Comment by tortilaman** [comment]
I would think adding documentation to make the limitation clear, along with that flag to fake it is probably sufficient for now.

That being said, in the thread you linked this [Jimp compatible gif tool](https://github.com/jtlapp/gifwrap) was mentioned. From an initial look it doesn't seem mature enough for production code, and I didn't see if it supports resizing.

I think a more important consideration though is that when using GIFs there's always a quality/filesize compromise (or challenge) that has to be overcome before even uploading. Would resizing gifs that a user (may have) spent a lot of time optimizing cause quality/filesize or optimization issues?

**Comment by tortilaman** [comment]
I'll work on a PR for faking it as I can.
